export const betebetProducts = [
  [
    {
      name: 'Классическая Маргарита',
      description: 'Традиционная пицца с моцареллой и томатным соусом.',
      image: require('../assets/product_1.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Пикантная Пепперони',
      description: 'Аппетитная пицца с кружочками пепперони и сыром.',
      image: require('../assets/product_2.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Сырный Микс',
      description: 'Четыре вида сыра на хрустящей основе.',
      image: require('../assets/product_3.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Тропическая Гавайская',
      description: 'Ананасы и ветчина на сочной основе с сыром.',
      image: require('../assets/product_4.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Овощное Ассорти',
      description: 'Свежие овощи с нежным сыром.',
      image: require('../assets/product_5.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Кремовая Карбонара',
      description: 'Бекон, яйцо и сливочный соус на сырной основе.',
      image: require('../assets/product_6.png'),
      price: 25,
      count: 1,
    },
  ],
  [
    {
      name: 'Зелёная Тоскана',
      description: 'Курица, песто и сушёные томаты на сырной основе.',
      image: require('../assets/product_7.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Мясной Микс',
      description: 'Ассорти из мясных ингредиентов с сыром.',
      image: require('../assets/product_8.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Острая Чоризо',
      description: 'Колбаса чоризо, грибы и кремовый соус.',
      image: require('../assets/product_9.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Морские Креветки',
      description: 'Креветки с чесноком и зеленью.',
      image: require('../assets/product_10.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Барбекю Курица',
      description: 'Курица, лук и перец в соусе барбекю.',
      image: require('../assets/product_11.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Острая Спайси',
      description: 'Халапеньо и острая пепперони на томатной основе.',
      image: require('../assets/product_12.png'),
      price: 25,
      count: 1,
    },
  ],
  [
    {
      name: 'Чесночный Хлеб',
      description: 'Хрустящий хлеб с чесноком и зеленью.',
      image: require('../assets/product_13.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Крылышки BBQ',
      description: 'Куриные крылышки в ароматном соусе барбекю.',
      image: require('../assets/product_14.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Золотистый Фри',
      description: 'Картофель фри с хрустящей корочкой.',
      image: require('../assets/product_15.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Кольца Кальмара',
      description: 'Хрустящие кальмары с соусом тар-тар.',
      image: require('../assets/product_16.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Свежий Капрезе',
      description: 'Моцарелла, томаты и базилик в оливковом масле.',
      image: require('../assets/product_17.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Сырные Начос',
      description: 'Хрустящие начос с растопленным сыром.',
      image: require('../assets/product_18.png'),
      price: 25,
      count: 1,
    },
  ],
  [
    {
      name: 'Итальянский Тирамису',
      description: 'Десерт с маскарпоне и кофейным ароматом.',
      image: require('../assets/product_19.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Ягодная Панна Котта',
      description: 'Кремовый десерт с ягодным соусом.',
      image: require('../assets/product_20.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Нежный Чизкейк',
      description: 'Сырный десерт с ягодным топпингом.',
      image: require('../assets/product_21.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Шоколадный Фондан',
      description: 'Кекс с жидким шоколадным центром.',
      image: require('../assets/product_22.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Фруктовая Феерия',
      description: 'Пицца с кремом и свежими фруктами.',
      image: require('../assets/product_23.png'),
      price: 25,
      count: 1,
    },
    {
      name: 'Кремовые Канноли',
      description: 'Трубочки с кремом и шоколадом.',
      image: require('../assets/product_24.png'),
      price: 25,
      count: 1,
    },
  ],
];

export const betebetAllProducts = betebetProducts.flat();
